# coding=utf-8

DEBUG = False

SECRET_KEY = 'Yzc1OTYzMTFkMTEwNDcyZDk2NzlmN2Rj'

ADMIN_NAME = u"后台管理"
FLASK_ADMIN_SWATCH = "Spacelab"

DATABASE_FILE = 'flask-base.sqlite'
SQLALCHEMY_DATABASE_URI = 'sqlite:///' + DATABASE_FILE
SQLALCHEMY_ECHO = False
SQLALCHEMY_TRACK_MODIFICATIONS = False

FORUMS_PER_PAGE = 10

# Flask-Security config
SECURITY_PASSWORD_HASH = "pbkdf2_sha512"
SECURITY_PASSWORD_SALT = "OTM1YWMyNGI4YWY4"

SECURITY_URL_PREFIX = "/admin"

SECURITY_LOGIN_URL = "/login/"
SECURITY_LOGOUT_URL = "/logout/"
SECURITY_REGISTER_URL = "/register/"

SECURITY_POST_LOGIN_VIEW = "/admin/"
SECURITY_POST_LOGOUT_VIEW = "/admin/"
SECURITY_POST_REGISTER_VIEW = "/admin/"

SECURITY_FLASH_MESSAGES = False
SECURITY_REGISTERABLE = False
SECURITY_SEND_REGISTER_EMAIL = False
